# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        ("schools", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee ID", max_length=50, unique=True
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Qualifications and certifications (one per line)",
                        null=True,
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        default=0, help_text="Years of experience in education"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Professional biography", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date trainer joined CAMDEEP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skills_expertise",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Skills this trainer specializes in",
                        related_name="expert_trainers",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(help_text="Assignment start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Assignment end date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("removed", "Removed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "visit_frequency",
                    models.CharField(
                        default="Twice per month",
                        help_text="Frequency of trainer visits",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Assignment notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program (optional, if school-wide leave blank)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainer_assignments",
                        to="programs.program",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_assignments",
                        to="schools.school",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        help_text="Assigned trainer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="trainer",
            name="assigned_schools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Schools this trainer is assigned to",
                related_name="trainers",
                through="trainers.TrainerAssignment",
                to="schools.school",
            ),
        ),
        migrations.CreateModel(
            name="TrainerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(help_text="Date of trainer visit")),
                (
                    "observations",
                    models.TextField(help_text="Observations and feedback"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Overall rating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommendations for improvement",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program feedback is about",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainer_feedbacks",
                        to="programs.program",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School subject of feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_feedbacks",
                        to="schools.school",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        help_text="Feedback provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.AddIndex(
            model_name="trainerassignment",
            index=models.Index(
                fields=["trainer", "status"], name="trainers_tr_trainer_091a72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerassignment",
            index=models.Index(
                fields=["school", "status"], name="trainers_tr_school__ad4975_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainerassignment",
            unique_together={("trainer", "school", "program")},
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["employee_id"], name="trainers_tr_employe_59870c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(fields=["status"], name="trainers_tr_status_84c60d_idx"),
        ),
        migrations.AddIndex(
            model_name="trainerfeedback",
            index=models.Index(
                fields=["trainer", "visit_date"], name="trainers_tr_trainer_66f1f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerfeedback",
            index=models.Index(
                fields=["school", "visit_date"], name="trainers_tr_school__ac91e4_idx"
            ),
        ),
    ]
