# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        ("schools", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Unique roll number", max_length=50, unique=True
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                        ],
                        help_text="Current grade level",
                        max_length=2,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Student date of birth", null=True
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True,
                        help_text="Parent/Guardian full name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "guardian_email",
                    models.EmailField(
                        blank=True,
                        help_text="Parent/Guardian email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        help_text="Parent/Guardian phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, help_text="Enrollment date in CAMDEEP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Enrolled school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentProgramEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, help_text="Enrollment date"),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, help_text="Program completion date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Progress percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="programs.program",
                    ),
                ),
                (
                    "school_program",
                    models.ForeignKey(
                        help_text="School-specific program implementation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="schools.schoolprogram",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Enrolled student",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentSkillProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        help_text="Current proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        help_text="Skill score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assessments_completed",
                    models.IntegerField(
                        default=0, help_text="Number of assessments completed"
                    ),
                ),
                (
                    "last_assessment_date",
                    models.DateField(
                        blank=True, help_text="Date of last assessment", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Trainer observations and notes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="Parent program enrollment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_progress",
                        to="students.studentprogramenrollment",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Associated skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["roll_number"], name="students_st_roll_nu_6ff92b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "grade"], name="students_st_school__e97f55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_st_status_5e2210_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprogramenrollment",
            index=models.Index(
                fields=["student", "status"], name="students_st_student_b77377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprogramenrollment",
            index=models.Index(
                fields=["program", "status"], name="students_st_program_9b63fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentprogramenrollment",
            unique_together={("student", "program", "school_program")},
        ),
        migrations.AddIndex(
            model_name="studentskillprogress",
            index=models.Index(
                fields=["enrollment", "skill"], name="students_st_enrollm_a03bd4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentskillprogress",
            unique_together={("enrollment", "skill")},
        ),
    ]
