# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, help_text="Date assessment was submitted", null=True
                    ),
                ),
                (
                    "grading_date",
                    models.DateTimeField(
                        blank=True, help_text="Date assessment was graded", null=True
                    ),
                ),
                (
                    "marks_obtained",
                    models.IntegerField(
                        blank=True,
                        help_text="Marks obtained",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Score percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(
                        default=False, help_text="Whether student passed the assessment"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback from grader", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_attempted", "Not Attempted"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="not_attempted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Assessment title", max_length=255),
                ),
                ("slug", models.SlugField()),
                (
                    "description",
                    models.TextField(
                        help_text="Assessment description and instructions"
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("worksheet", "Worksheet"),
                            ("quiz", "Quiz"),
                            ("project", "Project"),
                            ("activity", "Activity"),
                            ("assignment", "Assignment"),
                        ],
                        default="worksheet",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Assessment content")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF or document file",
                        null=True,
                        upload_to="assessments/",
                    ),
                ),
                (
                    "total_marks",
                    models.IntegerField(
                        default=100,
                        help_text="Total marks/points for this assessment",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "passing_percentage",
                    models.IntegerField(
                        default=50,
                        help_text="Passing percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Estimated time to complete (in minutes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
