# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="program_project",
            field=models.ForeignKey(
                help_text="Associated program project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="programs.programproject",
            ),
        ),
        migrations.AddField(
            model_name="studentassessmentresult",
            name="assessment",
            field=models.ForeignKey(
                help_text="Assessment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_results",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="studentassessmentresult",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
