# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassessmentresult",
            name="student",
            field=models.ForeignKey(
                help_text="Student",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_results",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["program_project", "status"],
                name="assessments_program_c1b737_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("program_project", "title")},
        ),
        migrations.AddIndex(
            model_name="studentassessmentresult",
            index=models.Index(
                fields=["student", "status"], name="assessments_student_690c24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentassessmentresult",
            index=models.Index(
                fields=["assessment", "is_passed"],
                name="assessments_assessm_4d43b3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentassessmentresult",
            unique_together={("student", "assessment")},
        ),
    ]
