# Generated by Django 6.0.4 on 2026-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or emoji",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="features/"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Welcome to CAMDEEP", max_length=255),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Empowering Minds. Transforming Futures.",
                        max_length=500,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "hero_description",
                    models.TextField(help_text="Hero section description"),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Get Started", max_length=100),
                ),
                (
                    "cta_button_url",
                    models.CharField(default="/programs", max_length=255),
                ),
                (
                    "featured_section_title",
                    models.CharField(default="Why Choose CAMDEEP?", max_length=255),
                ),
                (
                    "featured_section_description",
                    models.TextField(blank=True, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="CAMDEEP",
                        help_text="Official name of the platform",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="A Real-World Educational Framework with Global Competencies",
                        help_text="Official tagline",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField(help_text="Site description for SEO")),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(help_text="Primary phone", max_length=20),
                ),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Primary color (Blue)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Secondary color (White)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#D4AF37", help_text="Accent color (Gold)", max_length=7
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("allow_registration", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
