# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Testimonial author name", max_length=255
                    ),
                ),
                (
                    "author_title",
                    models.CharField(
                        blank=True,
                        help_text="Author title/role",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "author_image",
                    models.ImageField(
                        blank=True,
                        help_text="Author image/avatar",
                        null=True,
                        upload_to="cms/testimonials/",
                    ),
                ),
                ("content", models.TextField(help_text="Testimonial content")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        help_text="Rating (1-5 stars)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Feature on homepage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Blog post title", max_length=255),
                ),
                ("slug", models.SlugField(help_text="URL slug", unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short excerpt for listing", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Full blog content")),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Featured image", upload_to="cms/blog/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Blog category", max_length=100, null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags (comma-separated)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "read_time_minutes",
                    models.IntegerField(
                        default=5, help_text="Estimated read time in minutes"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="Publication date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of inquiry",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("replied", "Replied"),
                            ("resolved", "Resolved"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "replied_message",
                    models.TextField(blank=True, help_text="Reply message", null=True),
                ),
                (
                    "replied_date",
                    models.DateTimeField(
                        blank=True, help_text="Date message was replied to", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replied_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title", max_length=255, unique=True
                    ),
                ),
                ("slug", models.SlugField(help_text="URL slug", unique=True)),
                ("content", models.TextField(help_text="Page content (supports HTML)")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO keywords (comma-separated)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image",
                        null=True,
                        upload_to="cms/pages/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="Publication date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
