# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="related_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Related program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonials",
                to="programs.program",
            ),
        ),
    ]
