# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0002_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="related_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Related skill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonials",
                to="skills.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="cms_blogpos_slug_19f322_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["status"], name="cms_blogpos_status_c38b60_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["published_date"], name="cms_blogpos_publish_c8c5c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["status"], name="cms_contact_status_c39189_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["created_at"], name="cms_contact_created_c026b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["slug"], name="cms_page_slug_f9a361_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["status"], name="cms_page_status_3458bc_idx"),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(fields=["status"], name="cms_testimo_status_b0384b_idx"),
        ),
        migrations.AddIndex(
            model_name="testimonial",
            index=models.Index(
                fields=["featured"], name="cms_testimo_feature_830931_idx"
            ),
        ),
    ]
