# Generated by Django 6.0.4 on 2026-04-16 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique certificate ID",
                        unique=True,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        help_text="Achieved skill level",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "final_score",
                    models.IntegerField(
                        blank=True, help_text="Final score/percentage", null=True
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date certificate was issued"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Certificate expiry date (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF certificate",
                        null=True,
                        upload_to="certificates/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("issued", "Issued"), ("revoked", "Revoked")],
                        default="issued",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Certificate verification status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name", max_length=255, unique=True
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("skill", "Skill Certificate"),
                            ("program", "Program Certificate"),
                            ("completion", "Completion Certificate"),
                        ],
                        help_text="Type of certificate",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description", null=True
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="HTML or PDF template file",
                        upload_to="certificate_templates/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
