# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("programs", "0001_initial"),
        ("skills", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated program enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="students.studentprogramenrollment",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issued_by",
            field=models.ForeignKey(
                help_text="Issuing authority",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Program for which certificate is issued",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_certificates",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Skill for which certificate is issued",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_certificates",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="student",
            field=models.ForeignKey(
                help_text="Student receiving certificate",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated program (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate_templates",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated skill (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate_templates",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                help_text="Certificate template used",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_certificates",
                to="certificates.certificatetemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_id"], name="certificate_certifi_5672de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["student", "skill"], name="certificate_student_5a149d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="certificate_status_31e804_idx"),
        ),
    ]
