# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official school name", max_length=255, unique=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="School description", null=True
                    ),
                ),
                (
                    "principal_name",
                    models.CharField(
                        help_text="Principal or head of school name", max_length=255
                    ),
                ),
                ("principal_email", models.EmailField(max_length=254)),
                ("principal_phone", models.CharField(max_length=20)),
                (
                    "admin_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="CAMDEEP administrator contact name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        help_text="School administrator email",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("admin_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="schools/"),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("established_year", models.IntegerField(blank=True, null=True)),
                (
                    "total_students",
                    models.IntegerField(
                        default=0, help_text="Total number of students in school"
                    ),
                ),
                (
                    "target_grades",
                    models.CharField(
                        default="6,7,8,9,10",
                        help_text="Target grades (comma-separated)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "mou_signed",
                    models.BooleanField(
                        default=False, help_text="MOU signed and completed"
                    ),
                ),
                (
                    "mou_date",
                    models.DateField(
                        blank=True, help_text="Date MOU was signed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="schools_sch_slug_51c325_idx"),
                    models.Index(
                        fields=["status"], name="schools_sch_status_07bb06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        help_text="Grade level implementing this program", max_length=2
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Program start date in school"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Program end date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "number_of_students",
                    models.IntegerField(
                        default=0, help_text="Number of students enrolled"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Implementation notes and observations",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="CAMDEEP program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_implementations",
                        to="programs.program",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Partner school",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_programs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("school", "program", "grade_level")},
            },
        ),
    ]
