# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Module title", max_length=255)),
                ("content", models.TextField(help_text="Module content")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["project", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=255)),
                ("slug", models.SlugField()),
                (
                    "description",
                    models.TextField(help_text="Detailed project description"),
                ),
                (
                    "project_number",
                    models.IntegerField(
                        help_text="Project number (1 or 2) within the program",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=15, help_text="Project duration in days"
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="Project objectives (one per line)",
                        null=True,
                    ),
                ),
                (
                    "deliverables",
                    models.TextField(
                        blank=True,
                        help_text="Expected deliverables (one per line)",
                        null=True,
                    ),
                ),
                (
                    "resources",
                    models.TextField(
                        blank=True,
                        help_text="Required resources and materials",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["program", "order"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Program name", max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Detailed program description"),
                ),
                (
                    "target_grade",
                    models.CharField(
                        choices=[
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                        ],
                        help_text="Target grade level",
                        max_length=2,
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30,
                        help_text="Program duration in days",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="Key learning outcomes (one per line)",
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="programs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
