# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="skill",
            field=models.ForeignKey(
                help_text="Associated core skill",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="programproject",
            name="program",
            field=models.ForeignKey(
                help_text="Parent program",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="programmodule",
            name="project",
            field=models.ForeignKey(
                help_text="Parent project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="programs.programproject",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["slug"], name="programs_pr_slug_103929_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["status"], name="programs_pr_status_57a5e8_idx"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["skill"], name="programs_pr_skill_i_00b563_idx"),
        ),
        migrations.AddIndex(
            model_name="programproject",
            index=models.Index(
                fields=["program", "status"], name="programs_pr_program_f65eb0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programproject",
            unique_together={("program", "project_number")},
        ),
    ]
