# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name", max_length=255, unique=True
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("ngo", "NGO"),
                            ("corporate", "Corporate"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        help_text="Type of partner organization",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Partnership description", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospective", "Prospective"),
                            ("negotiating", "Negotiating"),
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                        ],
                        default="prospective",
                        max_length=20,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Primary contact person", max_length=255
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Partnership start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Partnership end date", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MOU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mou_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique MOU identifier",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Memorandum of Understanding with CAMDEEP",
                        help_text="MOU title",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="MOU description and objectives",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Partnership start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Partnership end date (optional)",
                        null=True,
                    ),
                ),
                (
                    "duration_months",
                    models.IntegerField(default=12, help_text="MOU duration in months"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Terms and conditions of partnership",
                        null=True,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        help_text="MOU document PDF",
                        null=True,
                        upload_to="mou/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Signature"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "signed_by_school_date",
                    models.DateField(
                        blank=True, help_text="Date signed by school", null=True
                    ),
                ),
                (
                    "signed_by_camdeep_date",
                    models.DateField(
                        blank=True, help_text="Date signed by CAMDEEP", null=True
                    ),
                ),
                (
                    "school_signatory_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of school signatory",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "school_signatory_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of school signatory",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "camdeep_signatory_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of CAMDEEP signatory",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "camdeep_signatory_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of CAMDEEP signatory",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mous",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MOU",
                "verbose_name_plural": "MOUs",
                "ordering": ["-created_at"],
            },
        ),
    ]
