# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partnerships", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mou",
            name="school",
            field=models.OneToOneField(
                help_text="Partner school",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mou",
                to="schools.school",
            ),
        ),
    ]
