# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("creativity", "Creativity"),
                            ("analytical", "Analytical Thinking"),
                            ("management", "Management Skills"),
                            ("digital", "Digital Skills"),
                            ("entrepreneurship", "Entrepreneurship"),
                            ("ethics", "Ethics"),
                            ("problem_solving", "Problem Solving"),
                        ],
                        help_text="Name of the core skill",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the skill"),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief description for listings", max_length=500
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or emoji representation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Skill banner image",
                        null=True,
                        upload_to="skills/",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="Key learning outcomes (one per line)",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order among skills"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the skill area/domain", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this skill area",
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Parent skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill", "order"],
            },
        ),
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        help_text="Proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of competency at this level"
                    ),
                ),
                (
                    "min_score",
                    models.IntegerField(
                        default=0, help_text="Minimum score to achieve this level"
                    ),
                ),
                (
                    "max_score",
                    models.IntegerField(
                        default=100, help_text="Maximum score for this level"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Associated skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill", "min_score"],
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["slug"], name="skills_skil_slug_2fd1f3_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_active"], name="skills_skil_is_acti_a22cb2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillarea",
            unique_together={("skill", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skilllevel",
            unique_together={("skill", "level")},
        ),
    ]
