# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=255, unique=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category description", null=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or emoji",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Resource title", max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(help_text="Resource description")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("article", "Article"),
                            ("worksheet", "Worksheet"),
                            ("template", "Template"),
                            ("tool", "Tool"),
                            ("other", "Other"),
                        ],
                        help_text="Type of resource",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Resource thumbnail image",
                        null=True,
                        upload_to="resources/thumbnails/",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Resource file for download",
                        null=True,
                        upload_to="resources/files/",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External link (for videos, articles, etc.)",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Resource author",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, help_text="Publication date", null=True
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, help_text="Number of downloads"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this resource on homepage"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_programs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related programs",
                        related_name="resources",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
