# Generated by Django 6.0.4 on 2026-04-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="related_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related skills",
                related_name="resources",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                help_text="Resource category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="resources.resourcecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["slug"], name="resources_r_slug_1bd26a_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["status"], name="resources_r_status_f37b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_featured"], name="resources_r_is_feat_66e011_idx"
            ),
        ),
    ]
